# Generated by Django 3.2.6 on 2021-09-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appdance', '0002_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Contact', models.BigIntegerField()),
                ('Place', models.CharField(max_length=100)),
            ],
        ),
    ]
